glesys-go v3.0.0
glesys/glesys-go pull request #42
Opened 2021-11-05 10:46 UTC by norrland

Move v3 code into base of project. Removes old v2 directory.

2021-11-05 11:02 UTC, norrland commented
Includes #41

2021-11-05 11:28 UTC, brother requested changes
Add a changelog stuff as well?

2021-11-09 12:56 UTC, norrland commented
Merge, then update the date for release in a new commit. Create release with tag. ???, profit.

2021-11-10 13:03 UTC, brother approved these changes
plz merge

2021-11-11 08:28 UTC, merged