Servers: begin deprecation of ServerDetails.State
glesys/glesys-go pull request #43
Opened 2022-09-16 12:56 UTC by norrland

Use IsLocked and IsRunning attributes in ServerDetails to get a more detailed state of the server rather than relying on the State attribute.

This will deprecate the IsRunning() and IsLocked() functions. Use the attributes directly instead.

2022-09-16 12:59 UTC, wecc commented
As this is a breaking change we should bump major to adhere to Semantic Versioning.

2022-09-16 13:03 UTC, brother requested changes
breaking.

2022-09-19 12:50 UTC, emil-nasso approved these changes

2022-09-19 20:12 UTC, brother approved these changes

2022-09-20 08:07 UTC, merged